name: Build and Deploy Quarkus to Fly.io

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Update Version and Build Native Quarkus App
        run: |
          mvn versions:set -DnewVersion=${{ github.run_number }}
      - name: Add properties to file
        run: |
          echo "budget.startdate=${{ vars.BUDGET_STARTDATE }}" >> src/main/resources/application.properties
          echo "quarkus.security.users.embedded.users.budget-user=${{ secrets.USER_PASSSWORD }}" >> src/main/resources/application.properties
          echo "quarkus.mongodb.connection-string=${{ secrets.MONGO_CONNECTION_URL }}" >> src/main/resources/application.properties

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
