name: Build and Deploy Quarkus to Fly.io

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Update Version and Build Native Quarkus App
        run: |
          new_version=$(date +"%Y%m%d%H%M%S")
          mvn versions:set -DnewVersion=$new_version

      - name: Add properties to file
        run: |
          echo "budget.startdate=${{ vars.BUDGET_STARTDATE }}" >> src/main/resources/application.properties
          echo "quarkus.http.auth.basic=true" >> src/main/resources/application.properties
          echo "quarkus.http.auth.policy.budget-policy.roles-allowed=budget" >> src/main/resources/application.properties
          echo "quarkus.http.auth.permission.budget-permission.paths=/budget*" >> src/main/resources/application.properties
          echo "quarkus.http.auth.permission.budget-permission.policy=budget-policy" >> src/main/resources/application.properties
          echo "quarkus.security.users.embedded.enabled=true" >> src/main/resources/application.properties
          echo "quarkus.security.users.embedded.plain-text=true" >> src/main/resources/application.properties
          echo "quarkus.security.users.embedded.roles.budget-user=budget" >> src/main/resources/application.properties
          echo "quarkus.mongodb.database=budget" >> src/main/resources/application.properties

      - name: log properties
        run: |
          cat src/main/resources/application.properties

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
